[package]
name = "fluvio-controlplane"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
description = "API for Fluvio Control Plane"
authors = ["fluvio.io"]
repository = "https://github.com/infinyon/fluvio"
publish = false

[lib]
name = "fluvio_controlplane"
path = "src/lib.rs"

[features]
use_serde = ["serde"]
k8 = ["use_serde", "fluvio-stream-model/k8"]

[dependencies]
tracing = { workspace = true }
serde = { workspace = true, features = ['derive'], optional = true }

# Fluvio dependencies
fluvio-types = { workspace = true  }
fluvio-controlplane-metadata = { workspace = true  }
fluvio-protocol = { workspace = true,  features = ["api","link"]}
fluvio-stream-model = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }