apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: upstreamclusters.fluvio.infinyon.com
spec:
  group: fluvio.infinyon.com
  scope: Namespaced
  names:
    kind: UpstreamCluster
    plural: upstreamclusters
    singular: upstreamcluster
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
          status: {}
      schema:
        openAPIV3Schema:
          required: ["spec"]
          type: object
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              required: ["sourceId","target", "keyPair"]
              properties:
                sourceId:
                  type: string
                target:
                  type: object
                  required: ["endpoint"]
                  properties:
                    endpoint:
                      type: string
                    tls:
                      type: object
                      properties:
                        domain:
                          type: string
                        caCert:
                          type: string
                        clientKey:
                          type: string
                        clientCert:
                          type: string
                keyPair:
                  type: object
                  required: ["publicKey"]
                  properties:
                    publicKey:
                      type: string
      additionalPrinterColumns:
        - name: Target
          type: string
          jsonPath: .spec.target.endpoint
   