apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: remoteclusters.fluvio.infinyon.com
spec:
  group: fluvio.infinyon.com
  scope: Namespaced
  names:
    kind: RemoteCluster
    plural: remoteclusters
    singular: remotecluster
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
          status: {}
      schema:
        openAPIV3Schema:
          required: ["spec"]
          type: object
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            spec:
              type: object
              required: ["remoteType"]
              properties:
                remoteType:
                  type: string
                  enum:
                    - MirrorEdge
                keyPair:
                  type: object
                  required: ["privateKey", "publicKey"]
                  properties:
                    publicKey:
                      type: string
                    privateKey:
                      type: string
      additionalPrinterColumns:
        - name: Remote Type
          type: string
          jsonPath: .spec.remoteType
   